;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                gamedefines.inc                             ;
;                            Binario Game Definitions                        ;
;                                   EE  10b                                  ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

.EQU    FIRST_GAME_ADDR = 0

.EQU    N_GAME_ROWS = 8
.EQU    N_GAME_COLS = 8

.EQU    N_GAME_COLORS = 3