.EQU    MSG_WELCOME_LEN     = 60
.EQU    MOV_STARBURST_LEN   = 7

.EQU    MSG_SCROLL_DELAY    = 10        ; Delay between scrolls of display 
                                        ; in tens of ms
.EQU    MOV_DELAY           = 25        ; Delay between images in animation
                                        ; in tens of ms
                                        
.EQU    MSG_TAB_WIDTH       = 2