;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                               tunesdefines.inc                             ;
;                           Speaker Music Definitions                        ;
;                                   EE  10b                                  ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;



; Tune lengths (notes)

.EQU    TUNE_MARIOCLEAR_LEN     = 30

; Musical notes

.EQU    NOTE_C6      = 1047
.EQU    NOTE_Ab5     = 831
.EQU    NOTE_Bb5     = 932
.EQU    NOTE_G5      = 784
.EQU    NOTE_F5      = 698
.EQU    NOTE_E5      = 659
.EQU    NOTE_Eb5     = 622
.EQU    NOTE_D5      = 587
.EQU    NOTE_Db5     = 554
.EQU    NOTE_C5      = 523
.EQU    NOTE_B4      = 494
.EQU    NOTE_Bb4     = 466
.EQU    NOTE_nA4     = 440
.EQU    NOTE_Ab4     = 415
.EQU    NOTE_G4      = 392
.EQU    NOTE_Gb4     = 370
.EQU    NOTE_F4      = 349
.EQU    NOTE_E4      = 330
.EQU    NOTE_Eb4     = 311
.EQU    NOTE_D4      = 294
.EQU    NOTE_Db4     = 277
.EQU    NOTE_C4      = 262
.EQU    NOTE_B3      = 247
.EQU    NOTE_Bb3     = 233
.EQU    NOTE_nA3     = 220
.EQU    NOTE_GS3     = 208
.EQU    NOTE_G3      = 196
.EQU    NOTE_Gb3     = 185
.EQU    NOTE_F3      = 175
.EQU    NOTE_E3      = 165