;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                              swencirhdlr.asm                               ;
;                 Homework #2 Encoder and Switch Interrupt Handler           ;
;                                   EE  10b                                  ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Description:      This Assembly file contains the Timer3CompareHandler 
;                   procedure that performs switch and encoder reading and 
;                   debouncing on a Timer3 CTC compare match for the EE 10b 
;                   Binario board
;
;
; Revision History:
;    5/04/18    Ray Sun         Initial revision.
;    5/05/18    Ray Sun         Updated documentation on stack depth and 
;                               changed registers.
;    5/05/18    Ray Sun         Changed procedure name and saved more registers.



; ################################ CODE SEGMENT ################################

.cseg



; Timer3CompareHandler:
; 
; Description         This procedure calls the switch and encoder debouncing 
;                     functions `SwDeb`, `LREncDeb`, and `UDEncDeb` when
;                     Timer3 generates a CTC output compare interrupt at a 
;                     specified constant rate `TIMER3RATE`.
; 
; Operation           When an output compare interrupt is generated by Timer3,
;                     the switch and encoder debouncing functions are called. 
;                     These functions poll the switch and encoder inputs and 
;                     set the corresponding flags for switch presses and encoder 
;                     rotation cycles.
; 
; Arguments           None.
; Return Values       None.
; 
; Global Variables    None.
; Shared Variables    None.
; Local Variables     None.
; 
; Inputs              None.
; Outputs             May set the six switch and encoder flags through the 
;                     switch and encoder debouncing functions. 
; 
; Error Handling      None.
; Algorithms          None.
; Data Structures     None.
; 
; Limitations         None.
; Known Bugs          None.
; Special Notes       None.
; 
; Registers Changed       R16
;       + Subroutines:    R0, R1, R17  
; Stack Depth             9 bytes
;
; Author              Ray Sun
; Last Modified       05/07/2018    

Timer3CompareHandler:
    PUSH    ZH                  ; Save Z, and Y
    PUSH    ZL
    PUSH    YH
    PUSH    YL
	PUSH    R17                 ; Save R0, R4, R16, and R17
    PUSH    R16                 ; R4 is saved because it is used by the test
	PUSH    R4                  ; code, albeit this is probably not necessary.
	PUSH    R0
    IN      R0,     SREG        ; Store status register (flags)
    PUSH    R0
    
    CLI                         ; Disable interrupts

    CALL    SwDeb               ; Do switch and encoder debouncing
    CALL    LREncDeb     
    CALL    UDEncDeb
    
    ;RJMP    DoneTimer3Compare   ; Done, so re-enable interrupts and return
    
 DoneTimer3Compare:
    POP     R0
    OUT     SREG,   R0          ; Restore status register
	POP     R0                  ; and R0, R4, R16, and R17
	POP     R4
    POP     R16                 
	POP     R17
    POP     YL                  ; Finally, restore Y and Z
    POP     YH 
    POP     ZL 
    POP     ZH 
    RETI                        ; Done, so return and reenable interrupts
