;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                              swencirhdlr.asm                               ;
;                 Homework #2 Encoder and Switch Interrupt Handler           ;
;                                   EE  10b                                  ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Description:      This Assembly file contains the Timer3CompareHandler 
;                   procedure that performs switch and encoder reading and 
;                   debouncing on a Timer3 CTC compare match for the EE 10b 
;                   Binario board
;
;
; Revision History:
;    5/04/18    Ray Sun         Initial version
;    5/05/18    Ray Sun         Updated documentation on stack depth and 
;                               changed registers.
;    5/05/18    Ray Sun         Changed procedure name and saved more registers.



; ################################ CODE SEGMENT ################################

.cseg



; Timer3InterruptHandler:
; 
; Description         This procedure calls the switch and encoder debouncing 
;                     functions `SwDeb()`, `LREncDeb()`, and `UDEncDeb()` when
;                     Timer3 generates a CTC output compare interrupt.
; 
; Operation           When a CTC output compare interrupt is generated by Timer3,
;                     the switch and encoder debouncing functions are called. 
;                     These functions poll the switch and encoder inputs and 
;                     set the corresponding flags for switch presses and encoder 
;                     rotation cycles.
; 
; Arguments           None.
; Return Values       None.
; 
; Global Variables    None.
; Shared Variables    lr_hasPress - Debounced left/right switch input
;                     ud_hasPress - Debounced up/down switch input
;                     lr_hasLeft - Have left/right encoder CCW rotation
;                     lr_hasRight - Have left/right encoder CW rotation
;                     ud_hasUp - Have up/down encoder CCW rotation
;                     ud_hasDown - Have up/down encoder CW rotation
;                     lr_enc_index - Left/right index for encoder table
;                     ud_enc_index - Up/down index for encoder table
; Local Variables     None.
; 
; Inputs              None.
; Outputs             May set the six switch and encoder flags through the switch 
;                     and encoder debouncing functions. 
; 
; Error Handling      None.
; Algorithms          None.
; Data Structures     None.
; 
; Limitations         None.
; Known Bugs          None.
; Special Notes       None.
; 
; Registers Changed       R16
;                             subroutines: R0, R1, R17  
; Stack Depth             6 bytes
;
; Author              Ray Sun
; Last Modified       05/04/2018    

Timer3CompareHandler:
    PUSH    ZH                  ; Save Z, Y, and R16 
    PUSH    ZL
    PUSH    YH
    PUSH    YL
	PUSH    R17
    PUSH    R16
	PUSH    R4
	PUSH    R0
    IN      R0,     SREG       ; Store status register (flags)
    PUSH    R0
    
    CLI                         ; Disable interrupts

    CALL    SwDeb               ; Do switch and encoder debouncing
    CALL    LREncDeb     
    CALL    UDEncDeb
    
    ; RJMP    DoneTimer3Compare   ; Done, so re-enable interrupts and return
    
 DoneTimer3Compare:
    POP     R0
    OUT     SREG,   R0          ; Restore status register
	POP     R0
	POP     R4
    POP     R16                 ; and R16, Y, and Z
	POP     R17
    POP     YL      
    POP     YH 
    POP     ZL 
    POP     ZH 
    RETI                        ; Done, so return and reenable interrupts
